import { Navigate, Route, Routes } from 'react-router-dom';
import AdminLayout from './AdminLayout';
import BookingsPage from '../pages/BookingsPage';
import EmployeesPage from '../pages/EmployeesPage';
import SalonPage from '../pages/SalonPage';
import TreatmentsPage from '../pages/TreatmentsPage';
import {
    ALL_EMPLOYEES_OPTION,
    dateToIso,
    formatDayLabel,
    isoToDate
} from '../utils/adminAppHelpers';

export default function AdminRoutes({
    loading,
    onRefresh,
    onLogout,
    sectionErrors,
    sectionSuccess,
    sortedBookableEmployees,
    filteredManualBookingEmployees,
    sortedTreatments,
    manualBookingEmployeeId,
    setManualBookingEmployeeId,
    manualBookingTreatmentId,
    setManualBookingTreatmentId,
    manualBookingDate,
    setManualBookingDate,
    manualBookingSlots,
    manualBookingSelectedSlot,
    setManualBookingSelectedSlot,
    handleManualBookingSlotSelect,
    manualBookingSlotsLoading,
    manualBookingHoldLoading,
    manualBookingForm,
    setManualBookingForm,
    manualBookingLookupLoading,
    manualBookingLookupMessage,
    clearFieldError,
    fieldErrors,
    clearSectionError,
    createAdminBooking,
    confirmedReviewOverview,
    confirmedReviewSearchQuery,
    setConfirmedReviewSearchQuery,
    refreshConfirmedReview,
    cancelBookingReview,
    bookingEditForm,
    setBookingEditForm,
    fillBookingEditForm,
    clearBookingEditForm,
    updateBookingReview,
    allBookingsOverview,
    bookingSearchQuery,
    setBookingSearchQuery,
    refreshAllBookings,
    bookingBlacklistEntries,
    bookingBlacklistForm,
    setBookingBlacklistForm,
    createBookingBlacklistEntry,
    deleteBookingBlacklistEntry,
    refreshBookingBlacklist,
    employeeForm,
    setEmployeeForm,
    sortedEmployees,
    selectedEmployeeId,
    setSelectedEmployeeId,
    selectedDate,
    setSelectedDate,
    employeeDay,
    setEmployeeDay,
    periodTargetEmployeeId,
    setPeriodTargetEmployeeId,
    periodStartDate,
    setPeriodStartDate,
    periodEndDate,
    setPeriodEndDate,
    employeePeriodDays,
    periodTemplateSourceEmployeeId,
    setPeriodTemplateSourceEmployeeId,
    periodTemplateWeekStart,
    setPeriodTemplateWeekStart,
    updateEmployeePeriodDay,
    createEmployee,
    updateEmployee,
    clearEmployeeForm,
    fillEmployeeForm,
    deleteEmployee,
    swapEmployees,
    updateEmployeePeriod,
    applyEmployeePeriodSalonDefaults,
    copyEmployeePeriodFromEmployee,
    repeatSelectedWeekPattern,
    updateEmployeeDay,
    treatmentForm,
    setTreatmentForm,
    createTreatment,
    updateTreatment,
    clearTreatmentForm,
    fillTreatmentForm,
    deleteTreatment,
    swapTreatments,
    hairSalonForm,
    setHairSalonForm,
    hairSalonHours,
    setHairSalonHours,
    updateHairSalon,
    updateSalonDay,
    copyMondayHoursToWeekdays,
    saveAllSalonHours
}) {
    return (
        <AdminLayout
            loading={loading}
            onRefresh={onRefresh}
            onLogout={onLogout}
            globalError={sectionErrors.global}
            globalSuccess={sectionSuccess.global}
        >
            <Routes>
                <Route path="/" element={<Navigate to="/bookings" replace />} />
                <Route
                    path="/bookings"
                    element={
                        <BookingsPage
                            sortedEmployees={sortedBookableEmployees}
                            filteredManualBookingEmployees={filteredManualBookingEmployees}
                            sortedTreatments={sortedTreatments}
                            manualBookingEmployeeId={manualBookingEmployeeId}
                            setManualBookingEmployeeId={(value) => {
                                setManualBookingEmployeeId(value);
                                setManualBookingSelectedSlot(null);
                                clearSectionError('adminBooking');
                            }}
                            manualBookingTreatmentId={manualBookingTreatmentId}
                            setManualBookingTreatmentId={(value) => {
                                setManualBookingTreatmentId(value);
                                setManualBookingSelectedSlot(null);
                                clearSectionError('adminBooking');
                            }}
                            manualBookingDate={manualBookingDate}
                            manualBookingDateObject={isoToDate(manualBookingDate)}
                            onManualBookingDateSelect={(date) => {
                                setManualBookingDate(dateToIso(date));
                                setManualBookingSelectedSlot(null);
                                clearSectionError('adminBooking');
                            }}
                            manualBookingSlots={manualBookingSlots}
                            manualBookingSelectedSlot={manualBookingSelectedSlot}
                            onManualBookingSlotSelect={handleManualBookingSlotSelect}
                            manualBookingSlotsLoading={manualBookingSlotsLoading}
                            manualBookingHoldLoading={manualBookingHoldLoading}
                            manualBookingForm={manualBookingForm}
                            setManualBookingForm={setManualBookingForm}
                            manualBookingLookupLoading={manualBookingLookupLoading}
                            manualBookingLookupMessage={manualBookingLookupMessage}
                            clearFieldError={clearFieldError}
                            fieldErrors={fieldErrors}
                            sectionErrors={sectionErrors}
                            sectionSuccess={sectionSuccess}
                            loading={loading}
                            createAdminBooking={createAdminBooking}
                            confirmedReviewOverview={confirmedReviewOverview}
                            confirmedReviewSearchQuery={confirmedReviewSearchQuery}
                            setConfirmedReviewSearchQuery={setConfirmedReviewSearchQuery}
                            refreshConfirmedReview={refreshConfirmedReview}
                            cancelBookingReview={cancelBookingReview}
                            bookingEditForm={bookingEditForm}
                            setBookingEditForm={setBookingEditForm}
                            fillBookingEditForm={fillBookingEditForm}
                            clearBookingEditForm={clearBookingEditForm}
                            updateBookingReview={updateBookingReview}
                            allBookingsOverview={allBookingsOverview}
                            bookingSearchQuery={bookingSearchQuery}
                            setBookingSearchQuery={setBookingSearchQuery}
                            refreshAllBookings={refreshAllBookings}
                            bookingBlacklistEntries={bookingBlacklistEntries}
                            bookingBlacklistForm={bookingBlacklistForm}
                            setBookingBlacklistForm={setBookingBlacklistForm}
                            createBookingBlacklistEntry={createBookingBlacklistEntry}
                            deleteBookingBlacklistEntry={deleteBookingBlacklistEntry}
                            refreshBookingBlacklist={refreshBookingBlacklist}
                        />
                    }
                />
                <Route
                    path="/employees"
                    element={
                        <EmployeesPage
                            employeeForm={employeeForm}
                            setEmployeeForm={setEmployeeForm}
                            sortedEmployees={sortedEmployees}
                            sortedBookableEmployees={sortedBookableEmployees}
                            sortedTreatments={sortedTreatments}
                            selectedEmployeeId={selectedEmployeeId}
                            setSelectedEmployeeId={setSelectedEmployeeId}
                            selectedDate={selectedDate}
                            setSelectedDate={setSelectedDate}
                            employeeDay={employeeDay}
                            setEmployeeDay={setEmployeeDay}
                            periodTargetEmployeeId={periodTargetEmployeeId}
                            setPeriodTargetEmployeeId={setPeriodTargetEmployeeId}
                            periodStartDate={periodStartDate}
                            setPeriodStartDate={setPeriodStartDate}
                            periodEndDate={periodEndDate}
                            setPeriodEndDate={setPeriodEndDate}
                            employeePeriodDays={employeePeriodDays}
                            periodTemplateSourceEmployeeId={periodTemplateSourceEmployeeId}
                            setPeriodTemplateSourceEmployeeId={setPeriodTemplateSourceEmployeeId}
                            periodTemplateWeekStart={periodTemplateWeekStart}
                            setPeriodTemplateWeekStart={setPeriodTemplateWeekStart}
                            updateEmployeePeriodDay={updateEmployeePeriodDay}
                            loading={loading}
                            clearFieldError={clearFieldError}
                            fieldErrors={fieldErrors}
                            sectionErrors={sectionErrors}
                            sectionSuccess={sectionSuccess}
                            createEmployee={createEmployee}
                            updateEmployee={updateEmployee}
                            clearEmployeeForm={clearEmployeeForm}
                            fillEmployeeForm={fillEmployeeForm}
                            deleteEmployee={deleteEmployee}
                            swapEmployees={swapEmployees}
                            updateEmployeePeriod={updateEmployeePeriod}
                            applyEmployeePeriodSalonDefaults={applyEmployeePeriodSalonDefaults}
                            copyEmployeePeriodFromEmployee={copyEmployeePeriodFromEmployee}
                            repeatSelectedWeekPattern={repeatSelectedWeekPattern}
                            updateEmployeeDay={updateEmployeeDay}
                            formatDayLabel={formatDayLabel}
                            allEmployeesOption={ALL_EMPLOYEES_OPTION}
                        />
                    }
                />
                <Route
                    path="/treatments"
                    element={
                        <TreatmentsPage
                            treatmentForm={treatmentForm}
                            setTreatmentForm={setTreatmentForm}
                            sortedTreatments={sortedTreatments}
                            loading={loading}
                            clearFieldError={clearFieldError}
                            fieldErrors={fieldErrors}
                            sectionErrors={sectionErrors}
                            sectionSuccess={sectionSuccess}
                            createTreatment={createTreatment}
                            updateTreatment={updateTreatment}
                            clearTreatmentForm={clearTreatmentForm}
                            fillTreatmentForm={fillTreatmentForm}
                            deleteTreatment={deleteTreatment}
                            swapTreatments={swapTreatments}
                        />
                    }
                />
                <Route
                    path="/salon"
                    element={
                        <SalonPage
                            hairSalonForm={hairSalonForm}
                            setHairSalonForm={setHairSalonForm}
                            hairSalonHours={hairSalonHours}
                            setHairSalonHours={setHairSalonHours}
                            clearFieldError={clearFieldError}
                            fieldErrors={fieldErrors}
                            loading={loading}
                            sectionErrors={sectionErrors}
                            sectionSuccess={sectionSuccess}
                            updateHairSalon={updateHairSalon}
                            updateSalonDay={updateSalonDay}
                            copyMondayHoursToWeekdays={copyMondayHoursToWeekdays}
                            saveAllSalonHours={saveAllSalonHours}
                        />
                    }
                />
                <Route path="*" element={<Navigate to="/bookings" replace />} />
            </Routes>
        </AdminLayout>
    );
}
