server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY:native}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.auth.cookie.secure=${APP_AUTH_COOKIE_SECURE:true}
app.auth.cookie.same-site=${APP_AUTH_COOKIE_SAME_SITE:None}
