package com.booking.engine.service;

import com.booking.engine.dto.BookingCheckoutSessionResponseDto;
import java.math.BigDecimal;
import java.util.Map;

/**
 * Service contract for stripe payment operations.
 * Defines stripe payment related business operations.
 *
 * @author Yehor
 * @version 1.0
 * @since March 2026
 */
public interface StripePaymentService {

    /**
     * Creates and confirms a card payment from a Stripe ConfirmationToken
     * generated by the frontend checkout elements.
     *
     * @param amount                booking payment amount in configured currency
     * @param customerEmail         receipt email
     * @param confirmationTokenId   Stripe confirmation token id
     * @param metadata              metadata map
     * @return checkout session payload with PaymentIntent id/client secret/status
     */
    BookingCheckoutSessionResponseDto createAndConfirmPaymentWithConfirmationToken(
            BigDecimal amount,
            String customerEmail,
            String confirmationTokenId,
            Map<String, String> metadata);

    /**
     * Creates and confirms an immediate booking payment using a saved payment method.
     *
     * @param amount          booking payment amount
     * @param customerEmail   receipt email
     * @param paymentMethodId Stripe card payment method id (test/live)
     * @param metadata        metadata map
     * @return Stripe PaymentIntent id
     */
    String createAndConfirmPayment(
            BigDecimal amount,
            String customerEmail,
            String paymentMethodId,
            Map<String, String> metadata);

    /**
     * Retrieves current PaymentIntent status string from Stripe.
     *
     * @param paymentIntentId Stripe PaymentIntent id
     * @return status string
     */
    String getPaymentIntentStatus(String paymentIntentId);
}
