package com.booking.engine.service;

import com.booking.engine.dto.BookingCheckoutSessionResponseDto;
import java.math.BigDecimal;
import java.util.Map;

/**
 * Service contract for stripe payment operations.
 * Defines stripe payment related business operations.
 */
public interface StripePaymentService {

    /**
     * Creates and confirms a card payment from a Stripe ConfirmationToken
     * generated by the frontend checkout elements.
     *
     * @param amount              booking payment amount in configured currency
     * @param customerEmail       receipt email
     * @param confirmationTokenId Stripe confirmation token id
     * @param metadata            metadata map
     * @return checkout session payload with PaymentIntent id/client secret/status
     */
    default BookingCheckoutSessionResponseDto createAndConfirmPaymentWithConfirmationToken(
            BigDecimal amount,
            String customerEmail,
            String confirmationTokenId,
            Map<String, String> metadata) {
        return createAndConfirmPaymentWithConfirmationTokenDetails(
                amount,
                customerEmail,
                confirmationTokenId,
                metadata).checkoutSession();
    }

    /**
     * Creates and confirms a card payment from a Stripe ConfirmationToken and
     * returns the PaymentIntent fields needed for local verification.
     *
     * @param amount              booking payment amount in configured currency
     * @param customerEmail       receipt email
     * @param confirmationTokenId Stripe confirmation token id
     * @param metadata            metadata map
     * @return checkout session payload and verified PaymentIntent snapshot
     */
    StripePaymentConfirmationResult createAndConfirmPaymentWithConfirmationTokenDetails(
            BigDecimal amount,
            String customerEmail,
            String confirmationTokenId,
            Map<String, String> metadata);

    /**
     * Creates and confirms an immediate booking payment using a saved payment
     * method.
     *
     * @param amount          booking payment amount
     * @param customerEmail   receipt email
     * @param paymentMethodId Stripe card payment method id (test/live)
     * @param metadata        metadata map
     * @return Stripe PaymentIntent id
     */
    String createAndConfirmPayment(
            BigDecimal amount,
            String customerEmail,
            String paymentMethodId,
            Map<String, String> metadata);

    /**
     * Retrieves current PaymentIntent status string from Stripe.
     *
     * @param paymentIntentId Stripe PaymentIntent id
     * @return status string
     */
    default String getPaymentIntentStatus(String paymentIntentId) {
        return getPaymentIntentDetails(paymentIntentId).status();
    }

    /**
     * Retrieves current PaymentIntent verification fields from Stripe.
     *
     * @param paymentIntentId Stripe PaymentIntent id
     * @return PaymentIntent snapshot
     */
    StripePaymentIntentDetails getPaymentIntentDetails(String paymentIntentId);
}
